//------------------------------------------------------------------------------
// <autogenerated>
//  手动创建代码,用于秒杀活动管理
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
    /// 秒杀活动
    /// </summary>
    [Table("tb_SeckillActivity")]
    public partial class ModelSeckillActivity : StringEntity
    {
        public ModelSeckillActivity()
        {
            this.ActivityName = string.Empty;
            this.ActivityDesc = string.Empty;
            this.StartTime = DateTime.Now;
            this.EndTime = DateTime.Now.AddDays(1);
            this.Status = SeckillActivityStatus.Pending;
            this.MaxPurchasePerUser = 1;
            this.IsDelete = 0;
            this.CreateTime = DateTime.Now;
        }

        /// <summary>
        /// 活动名称
        /// </summary>
        [Description("活动名称")]
        public string ActivityName { get; set; }

        /// <summary>
        /// 活动描述
        /// </summary>
        [Description("活动描述")]
        public string ActivityDesc { get; set; }

        /// <summary>
        /// 开始时间
        /// </summary>
        [Description("开始时间")]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// 结束时间
        /// </summary>
        [Description("结束时间")]
        public DateTime EndTime { get; set; }

        /// <summary>
        /// 活动状态(-10:已取消 0:待开始 10:进行中 20:已结束)
        /// </summary>
        [Description("活动状态")]
        public int Status { get; set; }

        /// <summary>
        /// 每人限购数量
        /// </summary>
        [Description("每人限购数量")]
        public int MaxPurchasePerUser { get; set; }

        /// <summary>
        /// 是否删除(0:未删除 1:已删除)
        /// </summary>
        [Description("是否删除")]
        public int IsDelete { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 创建人ID
        /// </summary>
        [Description("创建人ID")]
        [Browsable(false)]
        public string CreateUserId { get; set; }
    }

    /// <summary>
    /// 秒杀活动状态枚举
    /// </summary>
    public class SeckillActivityStatus
    {
        /// <summary>
        /// 已取消
        /// </summary>
        public const int Canceled = -10;
        /// <summary>
        /// 待开始
        /// </summary>
        public const int Pending = 0;
        /// <summary>
        /// 进行中
        /// </summary>
        public const int Ongoing = 10;
        /// <summary>
        /// 已结束
        /// </summary>
        public const int Ended = 20;
    }
}