//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 系统消息表
	/// </summary>
    [Table("tb_SysMessage")]
    public partial class ModelSysMessage : StringEntity
    { 
        public ModelSysMessage()
        {
          this.Type= 0;
          this.SubType= 0;
          this.SubTypeName= string.Empty;
          this.FromId= string.Empty;
          this.FromName= string.Empty;
          this.ToId= string.Empty;
          this.ToName= string.Empty;
          this.ToStatus= 0;
          this.Title= string.Empty;
          this.Content= string.Empty;
          this.Href= string.Empty;
          this.UserId= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 类型10:公告;20:消息;
        /// </summary>
        [Description("类型10:公告;20:消息;")]
        public int Type { get; set; }
        /// <summary>
        /// (10:平台消息;20:订单消息)
        /// </summary>
        [Description("(10:平台消息;20:订单消息)")]
        public int? SubType { get; set; }
        /// <summary>
        /// 子分类名称
        /// </summary>
        [Description("子分类名称")]
        public string SubTypeName { get; set; }
        /// <summary>
        /// 消息源用户Id
        /// </summary>
        [Description("消息源用户Id")]
        [Browsable(false)]
        public string FromId { get; set; }
        /// <summary>
        /// 消息源用户名
        /// </summary>
        [Description("消息源用户名")]
        public string FromName { get; set; }
        /// <summary>
        /// 消息送达用户Id
        /// </summary>
        [Description("消息送达用户Id")]
        [Browsable(false)]
        public string ToId { get; set; }
        /// <summary>
        /// 消息送达用户
        /// </summary>
        [Description("消息送达用户")]
        public string ToName { get; set; }
        /// <summary>
        /// 送达状态(-10:默认未读；10：已读)
        /// </summary>
        [Description("送达状态(-10:默认未读；10：已读)")]
        public int ToStatus { get; set; }
        /// <summary>
        /// 消息标题
        /// </summary>
        [Description("消息标题")]
        public string Title { get; set; }
        /// <summary>
        /// 消息内容
        /// </summary>
        [Description("消息内容")]
        public string Content { get; set; }
        /// <summary>
        /// 消息跳转页面
        /// </summary>
        [Description("消息跳转页面")]
        public string Href { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}