//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_Order")]
    public partial class ModelOrder : StringEntity
    { 
        public ModelOrder()
        {
          this.OrderNo= string.Empty;
          this.OrderStatus= ((10));
          this.IsRefund= ((-10));
          this.CouponId= string.Empty;
          this.PayType= ((10));
          this.PayUserId= string.Empty;
          this.OrderPrice= 0;
          this.TotalGoodsPrice= 0;
          this.CouponMoney= 0;
          this.PointsNum= 0;
          this.PointsMoney= 0;
          this.FreightPrice= 0;
          this.UpdatePrice= 0;
          this.PayPrice= 0;
          this.IsComment= ((-10));
          this.ParentId= string.Empty;
          this.SourceUserId= string.Empty;
          this.PayTime= DateTime.Now;
          this.SendTime= null;
          this.ArrivedTime= null;
          this.ReceivingTime= null;
          this.DoneTime= null;
          this.ExpressId= string.Empty;
          this.ExpressCompany= string.Empty;
          this.ExpressNo= string.Empty;
          this.PointsBonus= ((0));
          this.PayTransactionId= string.Empty;
          this.BuyerRemark= string.Empty;
          this.Platform= string.Empty;
          this.UserId= string.Empty;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 订单编号
        /// </summary>
        [Description("订单编号")]
        public string OrderNo { get; set; }
        /// <summary>
        /// 订单状态(-30:已取消 10:待付款 30:待发货 40:待收货 50:已送达 60:已收货 80:已完成)
        /// </summary>
        [Description("订单状态(-30:已取消 10:待付款 30:待发货 40:待收货 50:已送达 60:已收货 80:已完成)")]
        public int OrderStatus { get; set; }
        /// <summary>
        /// 是否售后(-10:非售后 10:售后)
        /// </summary>
        [Description("订单状态(-10:非售后 10:售后)")]
        public int IsRefund { get; set; }
        /// <summary>
        /// 优惠券ID
        /// </summary>
        [Description("优惠券ID")]
        [Browsable(false)]
        public string CouponId { get; set; }
        /// <summary>
        /// 支付方式(10余额支付 20微信支付 30云闪付)
        /// </summary>
        [Description("支付方式(10余额支付 20微信支付 30云闪付)")]
        public int PayType { get; set; }
        /// <summary>
        /// 支付人Id
        /// </summary>
        [Description("支付人Id")]
        [Browsable(false)]
        public string PayUserId { get; set; }
        /// <summary>
        /// 订单金额(优惠后,含运费)
        /// </summary>
        [Description("订单金额(优惠后,含运费)")]
        public decimal OrderPrice { get; set; }
        /// <summary>
        /// 商品总金额(不含优惠折扣)
        /// </summary>
        [Description("商品总金额(不含优惠折扣)")]
        public decimal TotalGoodsPrice { get; set; }
        /// <summary>
        /// 优惠券抵扣金额
        /// </summary>
        [Description("优惠券抵扣金额")]
        public decimal CouponMoney { get; set; }
        /// <summary>
        /// 积分抵扣数量(预留)
        /// </summary>
        [Description("积分抵扣数量(预留)")]
        public int? PointsNum { get; set; }
        /// <summary>
        /// 积分抵扣金额(预留)
        /// </summary>
        [Description("积分抵扣金额(预留)")]
        public decimal? PointsMoney { get; set; }
        /// <summary>
        /// 运费(车费)
        /// </summary>
        [Description("运)")]
        public decimal? FreightPrice { get; set; }
        /// <summary>
        /// 后台修改的订单金额
        /// </summary>
        [Description("后台修改的订单金额")]
        public decimal UpdatePrice { get; set; }
        /// <summary>
        /// 实际付款金额(包含运费)
        /// </summary>
        [Description("实际付款金额(包含运费)")]
        public decimal PayPrice { get; set; }
        /// <summary>
        /// 是否已评价(-10:否 10:是)
        /// </summary>
        [Description("是否已评价(-10:否 10:是)")]
        public int IsComment { get; set; }
        /// <summary>
        /// 父节点Id
        /// </summary>
        [Description("父节点Id")]
        [Browsable(false)]
        public string ParentId { get; set; }
        /// <summary>
        /// 来源Id(上下级,隔开)
        /// </summary>
        [Description("来源Id(上下级,隔开)")]
        [Browsable(false)]
        public string SourceUserId { get; set; }
        /// <summary>
        /// 付款时间
        /// </summary>
        [Description("付款时间")]
        public System.DateTime PayTime { get; set; }
        /// <summary>
        /// 发货时间
        /// </summary>
        [Description("发货时间")]
        public System.DateTime? SendTime { get; set; }
        /// <summary>
        /// 送达时间
        /// </summary>
        [Description("送达时间")]
        public System.DateTime? ArrivedTime { get; set; }
        /// <summary>
        /// 确认收货时间
        /// </summary>
        [Description("确认收货时间")]
        public System.DateTime? ReceivingTime { get; set; }
        /// <summary>
        /// 订单完成日期
        /// </summary>
        [Description("订单完成日期")]
        public System.DateTime? DoneTime { get; set; }
        /// <summary>
        /// 物流公司ID(预留)
        /// </summary>
        [Description("物流公司ID(预留)")]
        [Browsable(false)]
        public string ExpressId { get; set; }
        /// <summary>
        /// 物流公司(预留)
        /// </summary>
        [Description("物流公司(预留)")]
        public string ExpressCompany { get; set; }
        /// <summary>
        /// 物流单号(预留)
        /// </summary>
        [Description("物流单号(预留)")]
        public string ExpressNo { get; set; }
        /// <summary>
        /// 赠送的积分数量
        /// </summary>
        [Description("赠送的积分数量")]
        public decimal PointsBonus { get; set; }
        /// <summary>
        /// 支付交易号
        /// </summary>
        [Description("支付交易号")]
        [Browsable(false)]
        public string PayTransactionId { get; set; }
        /// <summary>
        /// 买家留言
        /// </summary>
        [Description("买家留言")]
        public string BuyerRemark { get; set; }
        /// <summary>
        /// 来源客户端
        /// </summary>
        [Description("来源客户端")]
        public string Platform { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        [Description("用户Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}