//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 商品规格组记录表
	/// </summary>
    [Table("tb_GoodsSpec")]
    public partial class ModelGoodsSpec : StringEntity
    { 
        public ModelGoodsSpec()
        {
          this.SpecName= string.Empty;
          this.GoodsId= string.Empty;
          this.SortNo= ((0));
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 规格组名称
        /// </summary>
        [Description("规格组名称")]
        public string SpecName { get; set; }
        /// <summary>
        /// 商品Id
        /// </summary>
        [Description("商品Id")]
        [Browsable(false)]
        public string GoodsId { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        [Description("排序")]
        public int SortNo { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}