//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 充值订单
	/// </summary>
    [Table("tb_RechargeOrder")]
    public partial class ModelRechargeOrder : StringEntity
    { 
        public ModelRechargeOrder()
        {
          this.OrderNo= string.Empty;
          this.RechargeType= 0;
          this.PlanId= string.Empty;
          this.PayPrice= 0;
          this.GiftMoney= 0;
          this.ActualMoney= 0;
          this.PayStatus= 0;
          this.PayTime= DateTime.Now;
          this.TransactionId= string.Empty;
          this.StoreId= string.Empty;
          this.UserId= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 订单编号
        /// </summary>
        [Description("订单编号")]
        public string OrderNo { get; set; }
        /// <summary>
        /// 充值方式(10:自定义金额 20:套餐充值)
        /// </summary>
        [Description("充值方式(10:自定义金额 20:套餐充值)")]
        public int RechargeType { get; set; }
        /// <summary>
        /// 套餐Id
        /// </summary>
        [Description("套餐Id")]
        [Browsable(false)]
        public string PlanId { get; set; }
        /// <summary>
        /// 支付金额
        /// </summary>
        [Description("支付金额")]
        public decimal PayPrice { get; set; }
        /// <summary>
        /// 赠送金额
        /// </summary>
        [Description("赠送金额")]
        public decimal GiftMoney { get; set; }
        /// <summary>
        /// 实际到账金额
        /// </summary>
        [Description("实际到账金额")]
        public decimal ActualMoney { get; set; }
        /// <summary>
        /// 支付状态(10:待支付 20:已支付)
        /// </summary>
        [Description("支付状态(10:待支付 20:已支付)")]
        public int PayStatus { get; set; }
        /// <summary>
        /// 付款时间
        /// </summary>
        [Description("付款时间")]
        public System.DateTime PayTime { get; set; }
        /// <summary>
        /// 第三方 支付交易号
        /// </summary>
        [Description("第三方 支付交易号")]
        [Browsable(false)]
        public string TransactionId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        [Description("用户Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}