//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 用户优惠券表
	/// </summary>
    [Table("tb_UserCoupon")]
    public partial class ModelUserCoupon : StringEntity
    { 
        public ModelUserCoupon()
        {
          this.CouponId= string.Empty;
          this.Name= string.Empty;
          this.Status= ((10));
          this.CouponType= ((10));
          this.SendType= ((10));
          this.ReducePrice= ((0));
          this.MinPrice= ((0));
          this.StartTime= DateTime.Now;
          this.EndTime= DateTime.Now;
          this.ApplyRange= ((10));
          this.ApplyRangeConfig= string.Empty;
          this.UserId= string.Empty;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
          this.UpdateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 优惠券Id
        /// </summary>
        [Description("优惠券Id")]
        [Browsable(false)]
        public string CouponId { get; set; }
        /// <summary>
        /// 优惠券名称
        /// </summary>
        [Description("优惠券名称")]
        public string Name { get; set; }
        /// <summary>
        /// 状态(-20:已使用 -10:已过期 10:可使用)
        /// </summary>
        [Description("状态(-20:已使用 -10:已过期 10:可使用)")]
        public int Status { get; set; }
        /// <summary>
        /// 优惠券类型(10:满减券 20:折扣券)
        /// </summary>
        [Description("优惠券类型(10:满减券 20:折扣券)")]
        public int? CouponType { get; set; }
        /// <summary>
        /// 发放方式:10:用户领取 20:系统发放
        /// </summary>
        [Description("发放方式:10:用户领取 20:系统发放")]
        public int SendType { get; set; }
        /// <summary>
        /// 满减券-减免金额
        /// </summary>
        [Description("满减券-减免金额")]
        public decimal ReducePrice { get; set; }
        /// <summary>
        /// 最低消费金额
        /// </summary>
        [Description("最低消费金额")]
        public decimal MinPrice { get; set; }
        /// <summary>
        /// 有效期开始时间
        /// </summary>
        [Description("有效期开始时间")]
        public System.DateTime StartTime { get; set; }
        /// <summary>
        /// 有效期结束时间
        /// </summary>
        [Description("有效期结束时间")]
        public System.DateTime EndTime { get; set; }
        /// <summary>
        /// 适用范围(10全部商品 20指定商品 30:排除商品)
        /// </summary>
        [Description("适用范围(10全部商品 20指定商品 30:排除商品)")]
        public int ApplyRange { get; set; }
        /// <summary>
        /// 适用范围(商品Id,隔开)
        /// </summary>
        [Description("适用范围(商品Id,隔开)")]
        public string ApplyRangeConfig { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        [Description("用户Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        [Description("更新时间")]
        public System.DateTime UpdateTime { get; set; }
    }
}