//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_OrderSku")]
    public partial class ModelOrderSku : StringEntity
    { 
        public ModelOrderSku()
        {
          this.OrderId= string.Empty;
          this.OrderNo= string.Empty;
          this.SubOrderNo= string.Empty;
          this.GoodsId= string.Empty;
          this.GoodsSkuId= string.Empty;
          this.OrderStatus= ((10));
          this.GoodsNo= string.Empty;
          this.GoodsName= string.Empty;
          this.SkuName= string.Empty;
          this.SkuImageId= string.Empty;
          this.DeductStockType= ((20));
          this.Quantity= 0;
          this.SalePrice= 0;
          this.PayPrice= 0;
          this.CouponMoney= 0;
          this.PointsMoney= ((0));
          this.PointsNum= ((0));
          this.Freight= 0;
          this.Commission1= 0;
          this.Commission2= 0;
          this.PointsBonus= ((0));
          this.StoreId= string.Empty;
          this.AfterSaleDeadlineTime= null;
          this.AfterSaleDeadline= 0;
          this.Unit= string.Empty;
          this.ExpressCompany= string.Empty;
          this.ExpressNo= string.Empty;
          this.IsComment= false;
          this.PayTime= null;
          this.SendTime= null;
          this.ReceivingTime= null;
          this.DoneTime= null;
          this.UserId= string.Empty;
          this.SourceUserId= string.Empty;
          this.IsRefund= ((-10));
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 订单ID 
        /// </summary>
        [Description("订单Id ")]
        [Browsable(false)]
        public string OrderId { get; set; }
        /// <summary>
        /// 订单编号
        /// </summary>
        [Description("订单编号")]
        public string OrderNo { get; set; }
        /// <summary>
        /// 子订单编号
        /// </summary>
        [Description("子订单编号")]
        public string SubOrderNo { get; set; }
        /// <summary>
        /// 商品Id
        /// </summary>
        [Description("商品Id")]
        [Browsable(false)]
        public string GoodsId { get; set; }
        /// <summary>
        /// SkuId唯一标识
        /// </summary>
        [Description("SkuId唯一标识")]
        [Browsable(false)]
        public string GoodsSkuId { get; set; }
        /// <summary>
        /// 订单状态(-50:售后 -10:未确认 10:拍照订单-待审核  20:待付款 30:待发货 40:待收货 80:已完成)
        /// </summary>
        [Description("订单状态(-50:售后 -10:未确认 10:拍照订单-待审核  20:待付款 30:待发货 40:待收货 80:已完成)")]
        public int OrderStatus { get; set; }
        /// <summary>
        /// 商品编号
        /// </summary>
        [Description("商品编号")]
        public string GoodsNo { get; set; }
        /// <summary>
        /// 商品名称
        /// </summary>
        [Description("商品名称")]
        public string GoodsName { get; set; }
        /// <summary>
        /// Sku名称
        /// </summary>
        [Description("Sku名称")]
        public string SkuName { get; set; }
        /// <summary>
        /// Sku图片Id
        /// </summary>
        [Description("Sku图片Id")]
        [Browsable(false)]
        public string SkuImageId { get; set; }
        /// <summary>
        /// 库存计算方式(10下单减库存 20付款减库存) 
        /// </summary>
        [Description("库存计算方式(10下单减库存 20付款减库存) ")]
        public int DeductStockType { get; set; }
        /// <summary>
        /// 购买数量
        /// </summary>
        [Description("购买数量")]
        public int Quantity { get; set; }
        /// <summary>
        /// 单价
        /// </summary>
        [Description("单价")]
        public decimal SalePrice { get; set; }
        /// <summary>
        /// 实际付款价(单价)
        /// </summary>
        [Description("实际付款价(单价)")]
        public decimal? PayPrice { get; set; }
        /// <summary>
        /// 优惠券折扣金额 
        /// </summary>
        [Description("优惠券折扣金额 ")]
        public decimal CouponMoney { get; set; }
        /// <summary>
        /// 积分金额(预留)
        /// </summary>
        [Description("积分金额(预留)")]
        public decimal? PointsMoney { get; set; }
        /// <summary>
        /// 积分抵扣数量(预留)
        /// </summary>
        [Description("积分抵扣数量(预留)")]
        public int? PointsNum { get; set; }
        /// <summary>
        /// 运费
        /// </summary>
        [Description("运费")]
        public decimal? Freight { get; set; }
        /// <summary>
        /// 一级提成
        /// </summary>
        [Description("一级提成")]
        public decimal? Commission1 { get; set; }
        /// <summary>
        /// 二级提成
        /// </summary>
        [Description("二级提成")]
        public decimal? Commission2 { get; set; }
        /// <summary>
        /// 赠送的积分数量
        /// </summary>
        [Description("赠送的积分数量")]
        public int PointsBonus { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 售后截止日期
        /// </summary>
        [Description("售后截止日期")]
        public System.DateTime? AfterSaleDeadlineTime { get; set; }
        /// <summary>
        /// 售后期限(天)
        /// </summary>
        [Description("售后期限(天)")]
        public int AfterSaleDeadline { get; set; }
        /// <summary>
        /// 单位
        /// </summary>
        [Description("单位")]
        public string Unit { get; set; }
        /// <summary>
        /// 物流公司(预留)
        /// </summary>
        [Description("物流公司(预留)")]
        public string ExpressCompany { get; set; }
        /// <summary>
        /// 物流单号(预留)
        /// </summary>
        [Description("物流单号(预留)")]
        public string ExpressNo { get; set; }
        /// <summary>
        /// 是否已评价(0否 1是)
        /// </summary>
        [Description("是否已评价(0否 1是)")]
        public bool IsComment { get; set; }
        /// <summary>
        /// 付款时间
        /// </summary>
        [Description("付款时间")]
        public System.DateTime? PayTime { get; set; }
        /// <summary>
        /// 发货时间
        /// </summary>
        [Description("发货时间")]
        public System.DateTime? SendTime { get; set; }
        /// <summary>
        /// 确认收货时间
        /// </summary>
        [Description("确认收货时间")]
        public System.DateTime? ReceivingTime { get; set; }
        /// <summary>
        /// 订单完成日期
        /// </summary>
        [Description("订单完成日期")]
        public System.DateTime? DoneTime { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        [Description("用户Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 来源Id(上下级,隔开)
        /// </summary>
        [Description("来源Id(上下级,隔开)")]
        [Browsable(false)]
        public string SourceUserId { get; set; }
        /// <summary>
        /// 订单状态(-10:非售后 10:售后)
        /// </summary>
        [Description("订单状态(-10:非售后 10:售后)")]
        public int IsRefund { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}