//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 充值快照
	/// </summary>
    [Table("tb_RechargeOrderPlan")]
    public partial class ModelRechargeOrderPlan : StringEntity
    { 
        public ModelRechargeOrderPlan()
        {
          this.OrderId= string.Empty;
          this.PlanId= string.Empty;
          this.PlanName= string.Empty;
          this.Money= 0;
          this.GiftMoney= 0;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 充值订单Id
        /// </summary>
        [Description("充值订单Id")]
        [Browsable(false)]
        public string OrderId { get; set; }
        /// <summary>
        /// 套餐Id
        /// </summary>
        [Description("套餐Id")]
        [Browsable(false)]
        public string PlanId { get; set; }
        /// <summary>
        /// 套餐名称
        /// </summary>
        [Description("套餐名称")]
        public string PlanName { get; set; }
        /// <summary>
        /// 充值金额
        /// </summary>
        [Description("充值金额")]
        public decimal Money { get; set; }
        /// <summary>
        /// 赠送金额
        /// </summary>
        [Description("赠送金额")]
        public decimal GiftMoney { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}