//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 商品评价
	/// </summary>
    [Table("tb_GoodsComment")]
    public partial class ModelGoodsComment : StringEntity
    { 
        public ModelGoodsComment()
        {
          this.Score= 0;
          this.Content= string.Empty;
          this.ImgIds= string.Empty;
          this.Status= 0;
          this.Sort= 0;
          this.OrderId= string.Empty;
          this.GoodsId= string.Empty;
          this.SkuId= string.Empty;
          this.UserId= string.Empty;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 评分
        /// </summary>
        [Description("评分")]
        public int Score { get; set; }
        /// <summary>
        /// 评价内容
        /// </summary>
        [Description("评价内容")]
        public string Content { get; set; }
        /// <summary>
        /// 图片Ids
        /// </summary>
        [Description("图片Ids")]
        [Browsable(false)]
        public string ImgIds { get; set; }
        /// <summary>
        /// 状态(-10:隐藏 10:显示)
        /// </summary>
        [Description("状态(-10:隐藏 10:显示)")]
        public int Status { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        [Description("排序")]
        public int Sort { get; set; }
        /// <summary>
        /// 订单Id
        /// </summary>
        [Description("订单Id")]
        [Browsable(false)]
        public string OrderId { get; set; }
        /// <summary>
        /// 商品Id
        /// </summary>
        [Description("商品Id")]
        [Browsable(false)]
        public string GoodsId { get; set; }
        /// <summary>
        /// SkuId
        /// </summary>
        [Description("SkuId")]
        [Browsable(false)]
        public string SkuId { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        [Description("用户Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}