//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 商品规格值记录表
	/// </summary>
    [Table("tb_GoodsSpecValue")]
    public partial class ModelGoodsSpecValue : StringEntity
    {
        public ModelGoodsSpecValue()
        {
          this.SpecValue= string.Empty;
          this.SpecId= string.Empty;
          this.GoodsId= string.Empty;
          this.Key= 0;
          this.CreateTime= DateTime.Now;
        }

        
        /// <summary>
        /// 规格值
        /// </summary>
        [Description("规格值")]
        public string SpecValue { get; set; }
        /// <summary>
        /// 规格组Id
        /// </summary>
        [Description("规格组Id")]
        [Browsable(false)]
        public string SpecId { get; set; }
        /// <summary>
        /// 商品Id
        /// </summary>
        [Description("商品Id")]
        [Browsable(false)]
        public string GoodsId { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        [Description("排序")]
        public int? SortNo { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        [Description("排序")]
        public int Key { get; set; }
        /// <summary>
        /// 规格组Key
        /// </summary>
        [Description("规格组Key")]
        public int? GroupKey { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}