//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_GoodsCate")]
    public partial class ModelGoodsCate : StringEntity
    { 
        public ModelGoodsCate()
        {
          this.Name= string.Empty;
          this.ParentId= string.Empty;
          this.Level= 0;
          this.ImageId= string.Empty;
          this.Status= ((10));
          this.SortNo= 0;
          this.CateId= string.Empty;
          this.Cate2Id= string.Empty;
          this.Cate3Id= string.Empty;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
          this.UpdateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 分类名
        /// </summary>
        [Description("分类名")]
        public string Name { get; set; }
        /// <summary>
        /// 父节点
        /// </summary>
        [Description("父节点Id")]
        [Browsable(false)]
        public string ParentId { get; set; }
        /// <summary>
        /// 层级
        /// </summary>
        [Description("层级")]
        public int? Level { get; set; }
        /// <summary>
        /// 图片Id
        /// </summary>
        [Description("图片Id")]
        [Browsable(false)]
        public string ImageId { get; set; }
        /// <summary>
        /// 状态(-10:不显示 10:显示)
        /// </summary>
        [Description("状态(-10:不显示 10:显示)")]
        public int Status { get; set; }
        /// <summary>
        /// 排序(小到大)
        /// </summary>
        [Description("排序(小到大)")]
        public int SortNo { get; set; }
        /// <summary>
        /// 一级分类ID
        /// </summary>
        [Description("一级分类ID")]
        [Browsable(false)]
        public string CateId { get; set; }
        /// <summary>
        /// 二级分类ID
        /// </summary>
        [Description("二级分类ID")]
        [Browsable(false)]
        public string Cate2Id { get; set; }
        /// <summary>
        /// 三级分类ID
        /// </summary>
        [Description("三级分类ID")]
        [Browsable(false)]
        public string Cate3Id { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public System.DateTime UpdateTime { get; set; }
    }
}