//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 提现明细表
	/// </summary>
    [Table("tb_UserDrawMoneyLog")]
    public partial class ModelUserDrawMoneyLog : StringEntity
    {
        public ModelUserDrawMoneyLog()
        {
            this.UserId = string.Empty;
            this.Money = 0;
            this.Describe = string.Empty;
            this.StoreId = string.Empty;
            this.CreateTime = DateTime.Now;
            this.BankCard = string.Empty;
            this.RealName = string.Empty;
            this.BankName = string.Empty;
            this.OpeningBankName = string.Empty;
            this.Status = 0;
            this.FailureRemark = string.Empty;
        }


        /// <summary>
        /// 用户Id
        /// </summary>
        [Description("用户Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 提现金额
        /// </summary>
        [Description("提现金额")]
        public decimal Money { get; set; }
        /// <summary>
        /// 提现后金额
        /// </summary>
        [Description("提现后金额")]
        public decimal? IncomeMoney { get; set; }
        /// <summary>
        /// 描述/说明
        /// </summary>
        [Description("描述/说明")]
        public string Describe { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 银行卡号
        /// </summary>
        [Description("银行卡号")]
        public string BankCard { get; set; }
        /// <summary>
        /// 真实姓名
        /// </summary>
        [Description("真实姓名")]
        public string RealName { get; set; }
        /// <summary>
        /// 银行
        /// </summary>
        [Description("银行")]
        public string BankName { get; set; }
        /// <summary>
        /// 开户行
        /// </summary>
        [Description("开户行")]
        public string OpeningBankName { get; set; }
        /// <summary>
        /// 提现状态（-10：提现失败 10：已申请  20：正在处理  50：提现成功）
        /// </summary>
        [Description("提现状态（-10：提现失败 10：已申请  20：正在处理  50：提现成功）")]
        public int Status { get; set; }
        /// <summary>
        /// 失败原因
        /// </summary>
        [Description("失败原因")]
        public string FailureRemark { get; set; }
    }
}