//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 快递鸟快递公司编码
	/// </summary>
    [Table("tb_ExpressCodeKuaiDiNiao")]
    public partial class ModelExpressCodeKuaiDiNiao : StringEntity
    { 
        public ModelExpressCodeKuaiDiNiao()
        {
          this.ExpressName= string.Empty;
          this.ExpressCode= string.Empty;
        }


        
        /// <summary>
        /// 快递公司名称
        /// </summary>
        [Description("快递公司名称")]
        public string ExpressName { get; set; }
        /// <summary>
        /// 快递公司编码
        /// </summary>
        [Description("快递公司编码")]
        public string ExpressCode { get; set; }
    }
}