//------------------------------------------------------------------------------
// <autogenerated>
//  手动生成代码,可以修改
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;
using Qs.Comm;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 秒杀活动管理
	/// </summary>
    [Table("tb_SeckillActivity")]
    public partial class ModelSeckillActivity : StringEntity
    { 
        public ModelSeckillActivity()
        {
          this.ActivityName= string.Empty;
          this.ActivityDesc= string.Empty;
          this.Status= (int)xEnum.SeckillActivityStatus.WaitStart;
          this.StartTime= DateTime.Now;
          this.EndTime= DateTime.Now.AddDays(1);
          this.LimitPerUser= 1;
          this.MaxRequestPerSecond= 100;
          this.StoreId= string.Empty;
          this.IsDelete= 0;
          this.CreateTime= DateTime.Now;
        }

        
        /// <summary>
        /// 活动名称
        /// </summary>
        [Description("活动名称")]
        public string ActivityName { get; set; }
        
        /// <summary>
        /// 活动描述
        /// </summary>
        [Description("活动描述")]
        public string ActivityDesc { get; set; }
        
        /// <summary>
        /// 活动状态(10:待开始 20:进行中 30:已结束 40:已取消)
        /// </summary>
        [Description("活动状态")]
        public int Status { get; set; }
        
        /// <summary>
        /// 开始时间
        /// </summary>
        [Description("开始时间")]
        public System.DateTime StartTime { get; set; }
        
        /// <summary>
        /// 结束时间
        /// </summary>
        [Description("结束时间")]
        public System.DateTime EndTime { get; set; }
        
        /// <summary>
        /// 用户限购数量
        /// </summary>
        [Description("用户限购数量")]
        public int LimitPerUser { get; set; }
        
        /// <summary>
        /// 每秒最大请求数
        /// </summary>
        [Description("每秒最大请求数")]
        public int MaxRequestPerSecond { get; set; }
        
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        public string StoreId { get; set; }
        
        /// <summary>
        /// 是否删除
        /// </summary>
        [Description("是否删除")]
        public int IsDelete { get; set; }
        
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}