//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_Article")]
    public partial class ModelArticle : StringEntity
    {
        public ModelArticle()
        {
          this.Title= string.Empty;
          this.ShowType= 0;
          this.CategoryId= string.Empty;
          this.ImageId= string.Empty;
          this.Content= string.Empty;
          this.Sort= 0;
          this.Status= 0;
          this.VirtualViews= string.Empty;
          this.ActualViews= string.Empty;
          this.IsDelete= string.Empty;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
          this.UpdateTime= DateTime.Now;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Title { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int ShowType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string CategoryId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string ImageId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Content { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int Sort { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int Status { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string VirtualViews { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string ActualViews { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string IsDelete { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime UpdateTime { get; set; }
    }
}