//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_InviteLink")]
    public partial class ModelInviteLink : StringEntity
    {
        public ModelInviteLink()
        {
          this.PosterId= string.Empty;
          this.InviterName= string.Empty;
          this.InviterPhone= string.Empty;
          this.UserId= string.Empty;
          this.CreateTime= DateTime.Now;
        }

        
        /// <summary>
        /// 海报ID
        /// </summary>
        [Description("海报Id")]
        [Browsable(false)]
        public string PosterId { get; set; }
        /// <summary>
        /// 邀请人名称
        /// </summary>
        [Description("邀请人名称")]
        public string InviterName { get; set; }
        /// <summary>
        /// 邀请人手机号
        /// </summary>
        [Description("邀请人手机号")]
        public string InviterPhone { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建人")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}