//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 文件
	/// </summary>
    [Table("FileUpload")]
    public partial class ModelFileUpload : StringEntity
    {
        public ModelFileUpload()
        {
          this.FileName= string.Empty;
          this.GroupId= string.Empty;
          this.Thumbnail= string.Empty;
          this.FilePath= string.Empty;
          this.Extension= string.Empty;
          this.SortNo= 0;
          this.StoreId= string.Empty;
          this.Description= string.Empty;
          this.CreateUserId= string.Empty;
          this.RoleIds= string.Empty;
          this.CreateUserName= string.Empty;
          this.CreateTime= DateTime.Now;
        }

        
        /// <summary>
        /// 文件名称
        /// </summary>
        [Description("文件名称")]
        public string FileName { get; set; }
        /// <summary>
        /// 分组Id
        /// </summary>
        [Description("分组Id")]
        [Browsable(false)]
        public string GroupId { get; set; }
        /// <summary>
        /// 文件类型 10:图片 20:附件 30:视频
        /// </summary>
        [Description("文件类型 10:图片 20:附件 30:视频")]
        public int? FileType { get; set; }
        /// <summary>
        /// 上传渠道 10:商户后端 20:用户端 50:管理后端 
        /// </summary>
        [Description("上传渠道 10:商户后端 20:用户端 50:管理后端 ")]
        public int? Channel { get; set; }
        /// <summary>
        /// 缩略图
        /// </summary>
        [Description("缩略图")]
        public string Thumbnail { get; set; }
        /// <summary>
        /// 文件路径
        /// </summary>
        [Description("文件路径")]
        public string FilePath { get; set; }
        /// <summary>
        /// 文件大小
        /// </summary>
        [Description("文件大小")]
        public int? FileSize { get; set; }
        /// <summary>
        /// 扩展名称
        /// </summary>
        [Description("扩展名称")]
        public string Extension { get; set; }
        /// <summary>
        /// 是否可用
        /// </summary>
        [Description("是否可用")]
        public bool Enable { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        [Description("排序")]
        public int SortNo { get; set; }
        /// <summary>
        /// 商家Id
        /// </summary>
        [Description("商家Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        [Description("描述")]
        public string Description { get; set; }
        /// <summary>
        /// 上传人
        /// </summary>
        [Description("上传人")]
        [Browsable(false)]
        public string CreateUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string RoleIds { get; set; }
        /// <summary>
        /// 上传人姓名
        /// </summary>
        [Description("上传人姓名")]
        public string CreateUserName { get; set; }
        /// <summary>
        /// 上传时间
        /// </summary>
        [Description("上传时间")]
        public System.DateTime CreateTime { get; set; }
    }
}