//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 商品服务承诺
	/// </summary>
    [Table("tb_GoodsService")]
    public partial class ModelGoodsService : StringEntity
    { 
        public ModelGoodsService()
        {
          this.ServiceName= string.Empty;
          this.Summary= string.Empty;
          this.IsDefault= 0;
          this.Status= 0;
          this.SortNo= 0;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 服务名称
        /// </summary>
        [Description("服务名称")]
        public string ServiceName { get; set; }
        /// <summary>
        /// 概述
        /// </summary>
        [Description("概述")]
        public string Summary { get; set; }
        /// <summary>
        /// 是否默认(10:是 -10:否)
        /// </summary>
        [Description("是否默认(10:是 -10:否)")]
        public int? IsDefault { get; set; }
        /// <summary>
        /// 状态 用户端是否展示(10:显示 -10:隐藏)
        /// </summary>
        [Description("状态 用户端是否展示(10:显示 -10:隐藏)")]
        public int? Status { get; set; }
        /// <summary>
        /// 排序(小到大)
        /// </summary>
        [Description("排序(小到大)")]
        public int? SortNo { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}