//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_InvitePoster")]
    public partial class ModelInvitePoster : StringEntity
    {
        public ModelInvitePoster()
        {
          this.PosterName= string.Empty;
          this.ImageId= string.Empty;
          this.CountRegUser= 0;
          this.UserId= string.Empty;
          this.CreateTime= DateTime.Now;
        }

        
        /// <summary>
        /// 海报名称
        /// </summary>
        [Description("海报名称")]
        public string PosterName { get; set; }
        /// <summary>
        /// 图片Id
        /// </summary>
        [Description("图片Id")]
        [Browsable(false)]
        public string ImageId { get; set; }
        /// <summary>
        /// 已邀请人数
        /// </summary>
        [Description("已邀请人数")]
        public int CountRegUser { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}