//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_InviteLinkRecord")]
    public partial class ModelInviteLinkRecord : StringEntity
    {
        public ModelInviteLinkRecord()
        {
          this.LinkId= string.Empty;
          this.PosterId= string.Empty;
          this.InviterId= string.Empty;
          this.InviterName= string.Empty;
          this.InviterPhone= string.Empty;
          this.Status= 0;
          this.InviteeUid= string.Empty;
          this.InviteeName= string.Empty;
          this.InviteePhone= string.Empty;
          this.InviteeCouponAmout= 0;
          this.InviteeCouponQuantity= 0;
          this.IsSendInviterCoupon= 0;
          this.IsSendInviteeCoupon= 0;
          this.CreateTime= DateTime.Now;
          this.InvitationTime= DateTime.Now;
          this.IsOpenVip= 0;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("链接Id")]
        [Browsable(false)]
        public string LinkId { get; set; }
        /// <summary>
        /// 类型(10:邀请 20:系统分配)
        /// </summary>
        [Description("类型(10:邀请 20:系统分配)")]
        public int? Type { get; set; }
        /// <summary>
        /// 海报Id
        /// </summary>
        [Description("海报Id")]
        [Browsable(false)]
        public string PosterId { get; set; }
        /// <summary>
        /// 邀请人Id
        /// </summary>
        [Description("邀请人Id")]
        [Browsable(false)]
        public string InviterId { get; set; }
        /// <summary>
        /// 邀请人名称
        /// </summary>
        [Description("邀请人名称")]
        public string InviterName { get; set; }
        /// <summary>
        /// 邀请人手机号
        /// </summary>
        [Description("邀请人手机号")]
        public string InviterPhone { get; set; }
        /// <summary>
        /// 被邀请人状态(10:已注册 20:已充会员)
        /// </summary>
        [Description("被邀请人状态(10:已注册 20:已充会员)")]
        public int Status { get; set; }
        /// <summary>
        /// 被邀请人Uid
        /// </summary>
        [Description("被邀请人Uid")]
        public string InviteeUid { get; set; }
        /// <summary>
        /// 被邀请人名称
        /// </summary>
        [Description("被邀请人名称")]
        public string InviteeName { get; set; }
        /// <summary>
        /// 被邀请人手机号码
        /// </summary>
        [Description("被邀请人手机号码")]
        public string InviteePhone { get; set; }
        /// <summary>
        /// 被邀请人代金券金额(预留)
        /// </summary>
        [Description("被邀请人代金券金额(预留)")]
        public decimal InviteeCouponAmout { get; set; }
        /// <summary>
        /// 优惠券数量
        /// </summary>
        [Description("优惠券数量")]
        public int InviteeCouponQuantity { get; set; }
        /// <summary>
        /// 是否已发送邀请人代金券
        /// </summary>
        [Description("是否已发送邀请人代金券")]
        public int IsSendInviterCoupon { get; set; }
        /// <summary>
        /// 是否已发送被邀请人代金券
        /// </summary>
        [Description("是否已发送被邀请人代金券")]
        public int IsSendInviteeCoupon { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 邀请时间
        /// </summary>
        [Description("邀请时间")]
        public System.DateTime InvitationTime { get; set; }
        /// <summary>
        /// 是否开通
        /// </summary>
        [Description("是否开通")]
        public int IsOpenVip { get; set; }
        /// <summary>
        /// 开通类型
        /// </summary>
        [Description("开通类型")]
        public int? OpenType { get; set; }
        /// <summary>
        /// 开通时间
        /// </summary>
        [Description("开通时间")]
        public System.DateTime? OpenTime { get; set; }
        /// <summary>
        /// 到期时间
        /// </summary>
        [Description("到期时间")]
        public System.DateTime? EndDate { get; set; }
    }
}