//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 用户收货地址表
	/// </summary>
    [Table("tb_UserAddress")]
    public partial class ModelUserAddress : StringEntity
    { 
        public ModelUserAddress()
        {
          this.Name= string.Empty;
          this.Phone= string.Empty;
          this.Province= string.Empty;
          this.City= string.Empty;
          this.Region= string.Empty;
          this.Detail= string.Empty;
          this.ProvinceId= string.Empty;
          this.CityId= string.Empty;
          this.RegionId= string.Empty;
          this.FullAddress= string.Empty;
          this.Longitude= 0;
          this.Latitude= 0;
          this.IsDefault= false;
          this.UserId= string.Empty;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 联系人
        /// </summary>
        [Description("联系人")]
        public string Name { get; set; }
        /// <summary>
        /// 联系电话
        /// </summary>
        [Description("联系电话")]
        public string Phone { get; set; }
        /// <summary>
        /// 省份
        /// </summary>
        [Description("省份")]
        public string Province { get; set; }
        /// <summary>
        /// 市
        /// </summary>
        [Description("市")]
        public string City { get; set; }
        /// <summary>
        /// 区/县
        /// </summary>
        [Description("区/县")]
        public string Region { get; set; }
        /// <summary>
        /// 详细地址
        /// </summary>
        [Description("详细地址")]
        public string Detail { get; set; }
        /// <summary>
        /// 省Id
        /// </summary>
        [Description("省Id")]
        [Browsable(false)]
        public string ProvinceId { get; set; }
        /// <summary>
        /// 市Id
        /// </summary>
        [Description("市Id")]
        [Browsable(false)]
        public string CityId { get; set; }
        /// <summary>
        /// 区/县Id
        /// </summary>
        [Description("区/县Id")]
        [Browsable(false)]
        public string RegionId { get; set; }
        /// <summary>
        /// 完整地址
        /// </summary>
        [Description("")]
        public string FullAddress { get; set; }
        /// <summary>
        /// 经度
        /// </summary>
        [Description("经度")]
        public decimal? Longitude { get; set; }
        /// <summary>
        /// 纬度
        /// </summary>
        [Description("纬度")]
        public decimal? Latitude { get; set; }
        /// <summary>
        /// 是否默认
        /// </summary>
        [Description("是否默认")]
        public bool IsDefault { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        [Description("用户Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}