//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_OrderTrack")]
    public partial class ModelOrderTrack : StringEntity
    { 
        public ModelOrderTrack()
        {
          this.OutTradeNo= string.Empty;
          this.Attach= string.Empty;
          this.Type= 0;
          this.Info= string.Empty;
          this.UserId= string.Empty;
          this.UserName= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 业务Id(商户保证唯一)
        /// </summary>
        [Description("业务Id(商户保证唯一)")]
        public string OutTradeNo { get; set; }
        /// <summary>
        /// 商户自定义参数(订单号等)
        /// </summary>
        [Description("商户自定义参数(订单号等)")]
        public string Attach { get; set; }
        /// <summary>
        /// 类型(10:订单 20:快递 50:售后)
        /// </summary>
        [Description("类型(10:订单 20:快递 50:售后)")]
        public int? Type { get; set; }
        /// <summary>
        /// 物流信息
        /// </summary>
        [Description("记录信息")]
        public string Info { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        [Description("用户Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 用户
        /// </summary>
        [Description("用户")]
        public string UserName { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}