//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_OrderAddress")]
    public partial class ModelOrderAddress : StringEntity
    { 
        public ModelOrderAddress()
        {
          this.AddressId= string.Empty;
          this.OrderId= string.Empty;
          this.Name= string.Empty;
          this.Phone= string.Empty;
          this.Province= string.Empty;
          this.City= string.Empty;
          this.Region= string.Empty;
          this.Detail= string.Empty;
          this.ProvinceId= string.Empty;
          this.CityId= string.Empty;
          this.RegionId= string.Empty;
          this.FullAddress= string.Empty;
          this.Longitude= 0;
          this.Latitude= 0;
          this.UserId= string.Empty;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string AddressId { get; set; }
        /// <summary>
        /// 订单Id
        /// </summary>
        [Description("订单Id")]
        [Browsable(false)]
        public string OrderId { get; set; }
        /// <summary>
        /// 收货人姓名
        /// </summary>
        [Description("收货人姓名")]
        public string Name { get; set; }
        /// <summary>
        /// 电话
        /// </summary>
        [Description("电话")]
        public string Phone { get; set; }
        /// <summary>
        /// 省
        /// </summary>
        [Description("省")]
        public string Province { get; set; }
        /// <summary>
        /// 市
        /// </summary>
        [Description("市")]
        public string City { get; set; }
        /// <summary>
        /// 区
        /// </summary>
        [Description("区")]
        public string Region { get; set; }
        /// <summary>
        /// 详细地址
        /// </summary>
        [Description("详细地址")]
        public string Detail { get; set; }
        /// <summary>
        /// 省份Id
        /// </summary>
        [Description("省份Id")]
        [Browsable(false)]
        public string ProvinceId { get; set; }
        /// <summary>
        /// 市Id
        /// </summary>
        [Description("市Id")]
        [Browsable(false)]
        public string CityId { get; set; }
        /// <summary>
        /// 区/县Id
        /// </summary>
        [Description("区/县Id")]
        [Browsable(false)]
        public string RegionId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string FullAddress { get; set; }
        /// <summary>
        /// 经度
        /// </summary>
        [Description("经度")]
        public decimal? Longitude { get; set; }
        /// <summary>
        /// 纬度
        /// </summary>
        [Description("纬度")]
        public decimal? Latitude { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        [Description("用户Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}