//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 购物车
	/// </summary>
    [Table("tb_Cart")]
    public partial class ModelCart : StringEntity
    { 
        public ModelCart()
        {
          this.GoodsId= string.Empty;
          this.GoodsSkuId= string.Empty;
          this.OrderId= string.Empty;
          this.SkuName= string.Empty;
          this.ImageId= string.Empty;
          this.SpecValueIds= string.Empty;
          this.SalePrice= 0;
          this.GoodsNum= 0;
          this.UserId= string.Empty;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string GoodsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string GoodsSkuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string OrderId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string SkuName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string ImageId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string SpecValueIds { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? SalePrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int GoodsNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime CreateTime { get; set; }
    }
}