//------------------------------------------------------------------------------
// <autogenerated>
//  手动生成代码,可以修改
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 秒杀用户抢购记录表
	/// </summary>
    [Table("tb_SeckillUserRecord")]
    public partial class ModelSeckillUserRecord : StringEntity
    { 
        public ModelSeckillUserRecord()
        {
          this.ActivityId= string.Empty;
          this.GoodsId= string.Empty;
          this.SkuId= string.Empty;
          this.UserId= string.Empty;
          this.BuyCount= 1;
          this.OrderId= string.Empty;
          this.CreateTime= DateTime.Now;
        }

        
        /// <summary>
        /// 秒杀活动ID
        /// </summary>
        [Description("秒杀活动ID")]
        public string ActivityId { get; set; }
        
        /// <summary>
        /// 商品ID
        /// </summary>
        [Description("商品ID")]
        public string GoodsId { get; set; }
        
        /// <summary>
        /// SKU ID
        /// </summary>
        [Description("SKU ID")]
        public string SkuId { get; set; }
        
        /// <summary>
        /// 用户ID
        /// </summary>
        [Description("用户ID")]
        public string UserId { get; set; }
        
        /// <summary>
        /// 购买数量
        /// </summary>
        [Description("购买数量")]
        public int BuyCount { get; set; }
        
        /// <summary>
        /// 生成的订单ID
        /// </summary>
        [Description("生成的订单ID")]
        public string OrderId { get; set; }
        
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}