//------------------------------------------------------------------------------
// <autogenerated>
//  手动创建代码,用于秒杀订单管理
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
    /// 秒杀订单
    /// </summary>
    [Table("tb_SeckillOrder")]
    public partial class ModelSeckillOrder : StringEntity
    {
        public ModelSeckillOrder()
        {
            this.OrderNo = string.Empty;
            this.ActivityId = string.Empty;
            this.GoodsId = string.Empty;
            this.SkuId = string.Empty;
            this.UserId = string.Empty;
            this.Quantity = 1;
            this.SeckillPrice = 0;
            this.TotalPrice = 0;
            this.Status = SeckillOrderStatus.PendingPay;
            this.CreateTime = DateTime.Now;
        }

        /// <summary>
        /// 订单编号
        /// </summary>
        [Description("订单编号")]
        public string OrderNo { get; set; }

        /// <summary>
        /// 秒杀活动ID
        /// </summary>
        [Description("秒杀活动ID")]
        [Browsable(false)]
        public string ActivityId { get; set; }

        /// <summary>
        /// 商品ID
        /// </summary>
        [Description("商品ID")]
        [Browsable(false)]
        public string GoodsId { get; set; }

        /// <summary>
        /// SKUID
        /// </summary>
        [Description("SKUID")]
        [Browsable(false)]
        public string SkuId { get; set; }

        /// <summary>
        /// 用户ID
        /// </summary>
        [Description("用户ID")]
        [Browsable(false)]
        public string UserId { get; set; }

        /// <summary>
        /// 购买数量
        /// </summary>
        [Description("购买数量")]
        public int Quantity { get; set; }

        /// <summary>
        /// 秒杀单价
        /// </summary>
        [Description("秒杀单价")]
        public decimal SeckillPrice { get; set; }

        /// <summary>
        /// 订单总价
        /// </summary>
        [Description("订单总价")]
        public decimal TotalPrice { get; set; }

        /// <summary>
        /// 订单状态(-10:已取消 0:待支付 10:已支付 20:已发货 30:已完成)
        /// </summary>
        [Description("订单状态")]
        public int Status { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 支付时间
        /// </summary>
        [Description("支付时间")]
        public DateTime? PayTime { get; set; }

        /// <summary>
        /// 发货时间
        /// </summary>
        [Description("发货时间")]
        public DateTime? ShipTime { get; set; }

        /// <summary>
        /// 完成时间
        /// </summary>
        [Description("完成时间")]
        public DateTime? CompleteTime { get; set; }
    }

    /// <summary>
    /// 秒杀订单状态枚举
    /// </summary>
    public class SeckillOrderStatus
    {
        /// <summary>
        /// 已取消
        /// </summary>
        public const int Canceled = -10;
        /// <summary>
        /// 待支付
        /// </summary>
        public const int PendingPay = 0;
        /// <summary>
        /// 已支付
        /// </summary>
        public const int Paid = 10;
        /// <summary>
        /// 已发货
        /// </summary>
        public const int Shipped = 20;
        /// <summary>
        /// 已完成
        /// </summary>
        public const int Completed = 30;
    }
}