//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("Sys_Area")]
    public partial class ModelSysArea : StringEntity
    {
        public ModelSysArea()
        {
          this.Name= string.Empty;
          this.FullName= string.Empty;
          this.ShortCode= string.Empty;
          this.ParentId= string.Empty;
          this.ParentShortCode= string.Empty;
          this.Province= string.Empty;
          this.City= string.Empty;
          this.District= string.Empty;
          this.Town= string.Empty;
          this.Village= string.Empty;
          this.Category= string.Empty;
          this.Country= string.Empty;
          this.Remark= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Name { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string FullName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string ShortCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string ParentId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string ParentShortCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? Level { get; set; }
        /// <summary>
        /// 省
        /// </summary>
        [Description("省")]
        public string Province { get; set; }
        /// <summary>
        /// 市
        /// </summary>
        [Description("市")]
        public string City { get; set; }
        /// <summary>
        /// 区县
        /// </summary>
        [Description("区县")]
        public string District { get; set; }
        /// <summary>
        /// 乡镇
        /// </summary>
        [Description("乡镇")]
        public string Town { get; set; }
        /// <summary>
        /// 村社区
        /// </summary>
        [Description("村社区")]
        public string Village { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Category { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Country { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? SortNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Remark { get; set; }
    }
}