//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// Role
	/// </summary>
    [Table("Role")]
    public partial class ModelRole : StringEntity
    { 
        public ModelRole()
        {
          this.Name= string.Empty;
          this.Type= 0;
          this.Status= 0;
          this.CreateId= string.Empty;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 角色名称
        /// </summary>
        [Description("角色名称")]
        public string Name { get; set; }
        /// <summary>
        /// 类型(10:平台 20:店铺)
        /// </summary>
        [Description("类型(10:平台 20:店铺)")]
        public int? Type { get; set; }
        /// <summary>
        /// 状态(-10:停用 10:正常)
        /// </summary>
        [Description("状态(-10:停用 10:正常)")]
        public int Status { get; set; }
        /// <summary>
        /// 创建人Id
        /// </summary>
        [Description("创建人Id")]
        [Browsable(false)]
        public string CreateId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}