//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 售后原因
	/// </summary>
    [Table("tb_RefundReason")]
    public partial class ModelRefundReason : StringEntity
    { 
        public ModelRefundReason()
        {
          this.ParentId= string.Empty;
          this.Level= 0;
          this.SortNo= 0;
          this.Code= 0;
          this.Value= string.Empty;
          this.Title= string.Empty;
          this.Description= string.Empty;
          this.IsDelete= 0;
          this.CreateTime= null;
        }


        
        /// <summary>
        /// 父节点Id
        /// </summary>
        [Description("父节点Id")]
        [Browsable(false)]
        public string ParentId { get; set; }
        /// <summary>
        /// 层级
        /// </summary>
        [Description("层级")]
        public int? Level { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        [Description("排序")]
        public int? SortNo { get; set; }
        /// <summary>
        /// 编号
        /// </summary>
        [Description("编号")]
        public int? Code { get; set; }
        /// <summary>
        /// 值
        /// </summary>
        [Description("值")]
        public string Value { get; set; }
        /// <summary>
        /// 原因
        /// </summary>
        [Description("原因")]
        public string Title { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        [Description("描述")]
        public string Description { get; set; }
        /// <summary>
        /// 是否已删除
        /// </summary>
        [Description("是否已删除")]
        public int? IsDelete { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime? CreateTime { get; set; }
    }
}