//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 唯品尚 异步通知接收
	/// </summary>
    [Table("tb_WpsNotify")]
    public partial class ModelWpsNotify : StringEntity
    { 
        public ModelWpsNotify()
        {
          this.Type= 0;
          this.Status= ((10));
          this.Content= string.Empty;
          this.CreateTime= DateTime.Now;
        }

        
        /// <summary>
        /// 类型 (2:价格变更 4:上下架变更 6:商品池(可选) 16:商品详情变更 23:订单配送消息 28:售后进度消息 29:售后地址推送 30:已选商品推送)
        /// </summary>
        [Description("类型 (2:价格变更 4:上下架变更 6:商品池(可选) 16:商品详情变更 23:订单配送消息 28:售后进度消息 29:售后地址推送 30:已选商品推送)")]
        public int? Type { get; set; }
        /// <summary>
        /// 状态(10:已处理 -10:未处理)
        /// </summary>
        [Description("状态(10:已处理 -10:未处理)")]
        public int? Status { get; set; }
        /// <summary>
        /// 内容
        /// </summary>
        [Description("内容")]
        public string Content { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}