//------------------------------------------------------------------------------
// <autogenerated>
//  手动创建代码,用于秒杀商品管理
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
    /// 秒杀商品
    /// </summary>
    [Table("tb_SeckillGoods")]
    public partial class ModelSeckillGoods : StringEntity
    {
        public ModelSeckillGoods()
        {
            this.ActivityId = string.Empty;
            this.GoodsId = string.Empty;
            this.SkuId = string.Empty;
            this.SeckillPrice = 0;
            this.SeckillStock = 0;
            this.SoldQuantity = 0;
            this.IsActive = true;
            this.CreateTime = DateTime.Now;
        }

        /// <summary>
        /// 秒杀活动ID
        /// </summary>
        [Description("秒杀活动ID")]
        [Browsable(false)]
        public string ActivityId { get; set; }

        /// <summary>
        /// 商品ID
        /// </summary>
        [Description("商品ID")]
        [Browsable(false)]
        public string GoodsId { get; set; }

        /// <summary>
        /// SKUID
        /// </summary>
        [Description("SKUID")]
        [Browsable(false)]
        public string SkuId { get; set; }

        /// <summary>
        /// 秒杀价格
        /// </summary>
        [Description("秒杀价格")]
        public decimal SeckillPrice { get; set; }

        /// <summary>
        /// 秒杀库存
        /// </summary>
        [Description("秒杀库存")]
        public int SeckillStock { get; set; }

        /// <summary>
        /// 已售数量
        /// </summary>
        [Description("已售数量")]
        public int SoldQuantity { get; set; }

        /// <summary>
        /// 是否有效
        /// </summary>
        [Description("是否有效")]
        public bool IsActive { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public DateTime CreateTime { get; set; }
    }
}