//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// tb_OrderRefundSku
	/// </summary>
    [Table("tb_OrderRefundSku")]
    public partial class ModelOrderRefundSku : StringEntity
    { 
        public ModelOrderRefundSku()
        {
          this.RefundNo= string.Empty;
          this.OrderId= string.Empty;
          this.OrderNo= string.Empty;
          this.CurrentOrderStatus= 0;
          this.OrderSkuId= string.Empty;
          this.GoodsId= string.Empty;
          this.GoodsName= string.Empty;
          this.SkuId= string.Empty;
          this.SkuName= string.Empty;
          this.SkuImageId= string.Empty;
          this.RefundType= 0;
          this.Status= 0;
          this.AmountExpectRefund= 0;
          this.AmountRealRefund= 0;
          this.RefundProof= string.Empty;
          this.RefundReason= string.Empty;
          this.Mark= string.Empty;
          this.SellerMark= string.Empty;
          this.RefundQuantity= 0;
          this.UserId= string.Empty;
          this.ExpressCompany= string.Empty;
          this.ExpressNo= string.Empty;
          this.CreateTime= DateTime.Now;
          this.AuditTime= null;
          this.DeliveryTime= null;
          this.RefundTime= null;
          this.StoreId= string.Empty;
        }


        
        /// <summary>
        /// 售后单编号
        /// </summary>
        [Description("售后单编号")]
        public string RefundNo { get; set; }
        /// <summary>
        /// 订单Id
        /// </summary>
        [Description("订单Id")]
        [Browsable(false)]
        public string OrderId { get; set; }
        /// <summary>
        /// 订单编号
        /// </summary>
        [Description("订单编号")]
        public string OrderNo { get; set; }
        /// <summary>
        /// 订单状态(申请售后时)
        /// </summary>
        [Description("订单状态(申请售后时)")]
        public int? CurrentOrderStatus { get; set; }
        /// <summary>
        /// 订单SkuId
        /// </summary>
        [Description("订单SkuId")]
        [Browsable(false)]
        public string OrderSkuId { get; set; }
        /// <summary>
        /// 商品Id
        /// </summary>
        [Description("商品Id")]
        [Browsable(false)]
        public string GoodsId { get; set; }
        /// <summary>
        /// 商品名称
        /// </summary>
        [Description("商品名称")]
        public string GoodsName { get; set; }
        /// <summary>
        /// SkuId
        /// </summary>
        [Description("SkuId")]
        [Browsable(false)]
        public string SkuId { get; set; }
        /// <summary>
        /// Sku名称
        /// </summary>
        [Description("Sku名称")]
        public string SkuName { get; set; }
        /// <summary>
        /// Sku图片
        /// </summary>
        [Description("Sku图片")]
        [Browsable(false)]
        public string SkuImageId { get; set; }
        /// <summary>
        /// 售后类型(10:退货退款 20:仅退款)
        /// </summary>
        [Description("售后类型(10:退货退款 20:仅退款)")]
        public int? RefundType { get; set; }
        /// <summary>
        /// 售后状态(-10:审核拒绝 10:等待审核 20:审核通过 30:已发货 40:已收货 80:已退款)
        /// </summary>
        [Description("售后状态(-10:审核拒绝 10:等待审核 20:审核通过 30:已发货 40:已收货 80:已退款)")]
        public int? Status { get; set; }
        /// <summary>
        /// 期望退款金额
        /// </summary>
        [Description("期望退款金额")]
        public decimal? AmountExpectRefund { get; set; }
        /// <summary>
        /// 实际退款金额
        /// </summary>
        [Description("实际退款金额")]
        public decimal? AmountRealRefund { get; set; }
        /// <summary>
        /// 售后凭证(图片/视频)
        /// </summary>
        [Description("售后凭证(图片/视频)")]
        public string RefundProof { get; set; }
        /// <summary>
        /// 退款原因
        /// </summary>
        [Description("退款原因")]
        public string RefundReason { get; set; }
        /// <summary>
        /// 用户备注
        /// </summary>
        [Description("用户备注")]
        public string Mark { get; set; }
        /// <summary>
        /// 卖家备注(审核失败,显示到前端)
        /// </summary>
        [Description("卖家备注(审核失败,显示到前端)")]
        public string SellerMark { get; set; }
        /// <summary>
        /// 售后数量
        /// </summary>
        [Description("售后数量")]
        public int? RefundQuantity { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        [Description("用户ID")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 物流公司(预留)
        /// </summary>
        [Description("物流公司(预留)")]
        public string ExpressCompany { get; set; }
        /// <summary>
        /// 物流单号(预留)
        /// </summary>
        [Description("物流单号(预留)")]
        public string ExpressNo { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 审核时间
        /// </summary>
        [Description("审核时间")]
        public System.DateTime? AuditTime { get; set; }
        /// <summary>
        /// 发货时间
        /// </summary>
        [Description("发货时间")]
        public System.DateTime? DeliveryTime { get; set; }
        /// <summary>
        /// 收货退款时间
        /// </summary>
        [Description("收货退款时间")]
        public System.DateTime? RefundTime { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
    }
}