//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 系统设置
	/// </summary>
    [Table("tb_SysSetting")]
    public partial class ModelSysSetting : StringEntity
    {
        public ModelSysSetting()
        {
          this.Key= string.Empty;
          this.Describe= string.Empty;
          this.Values= string.Empty;
          this.CreateTime= DateTime.Now;
        }

        
        /// <summary>
        /// 设置项标示
        /// </summary>
        [Description("设置项标识")]
        public string Key { get; set; }
        /// <summary>
        /// 设置项描述
        /// </summary>
        [Description("设置项描述")]
        public string Describe { get; set; }
        /// <summary>
        /// 设置内容（json格式）
        /// </summary>
        [Description("设置内容（json格式）")]
        public string Values { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}