//------------------------------------------------------------------------------
// <autogenerated>
//  手动生成代码,可以修改
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 秒杀商品关联表
	/// </summary>
    [Table("tb_SeckillGoods")]
    public partial class ModelSeckillGoods : StringEntity
    { 
        public ModelSeckillGoods()
        {
          this.ActivityId= string.Empty;
          this.GoodsId= string.Empty;
          this.SkuId= string.Empty;
          this.SeckillPrice= 0;
          this.SeckillStock= 0;
          this.SoldCount= 0;
          this.SortNo= 0;
          this.IsDelete= 0;
          this.CreateTime= DateTime.Now;
        }

        
        /// <summary>
        /// 秒杀活动ID
        /// </summary>
        [Description("秒杀活动ID")]
        public string ActivityId { get; set; }
        
        /// <summary>
        /// 商品ID
        /// </summary>
        [Description("商品ID")]
        public string GoodsId { get; set; }
        
        /// <summary>
        /// SKU ID
        /// </summary>
        [Description("SKU ID")]
        public string SkuId { get; set; }
        
        /// <summary>
        /// 秒杀价格
        /// </summary>
        [Description("秒杀价格")]
        public decimal SeckillPrice { get; set; }
        
        /// <summary>
        /// 秒杀库存
        /// </summary>
        [Description("秒杀库存")]
        public int SeckillStock { get; set; }
        
        /// <summary>
        /// 已售数量
        /// </summary>
        [Description("已售数量")]
        public int SoldCount { get; set; }
        
        /// <summary>
        /// 排序编号
        /// </summary>
        [Description("排序编号")]
        public int SortNo { get; set; }
        
        /// <summary>
        /// 是否删除
        /// </summary>
        [Description("是否删除")]
        public int IsDelete { get; set; }
        
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
        
        /// <summary>
        /// 导航属性：秒杀活动
        /// </summary>
        [ForeignKey("ActivityId")]
        public virtual ModelSeckillActivity Activity { get; set; }
        
        /// <summary>
        /// 导航属性：商品
        /// </summary>
        [ForeignKey("GoodsId")]
        public virtual ModelGoods Goods { get; set; }
    }
}