//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_Delivery")]
    public partial class ModelDelivery : StringEntity
    { 
        public ModelDelivery()
        {
          this.Name= string.Empty;
          this.Method= 0;
          this.Sort= 0;
          this.StoreId= string.Empty;
          this.CreateTime= DateTime.Now;
          this.UpdateTime= DateTime.Now;
        }


        
        /// <summary>
        /// 模板名称
        /// </summary>
        [Description("模板名称")]
        public string Name { get; set; }
        /// <summary>
        /// 计费方式(10按件数 20按重量)
        /// </summary>
        [Description("计费方式(10按件数 20按重量)")]
        public int Method { get; set; }
        /// <summary>
        /// 排序方式(数字越小越靠前)
        /// </summary>
        [Description("排序方式(数字越小越靠前)")]
        public int Sort { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public System.DateTime UpdateTime { get; set; }
    }
}