//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// tb_Store
	/// </summary>
    [Table("tb_Store")]
    public partial class ModelStore : StringEntity
    { 
        public ModelStore()
        {
          this.StoreName= string.Empty;
          this.LogoImageId= string.Empty;
          this.Status= 0;
          this.Describe= string.Empty;
          this.LinkMan= string.Empty;
          this.Phone= string.Empty;
          this.CompanyName= string.Empty;
          this.DeadLineDate= null;
          this.StoreId= string.Empty;
          this.CreateTime= null;
        }


        
        /// <summary>
        /// 商城名称
        /// </summary>
        [Description("商城名称")]
        public string StoreName { get; set; }
        /// <summary>
        /// Logo
        /// </summary>
        [Description("Logo")]
        [Browsable(false)]
        public string LogoImageId { get; set; }
        /// <summary>
        /// 状态(-10:闭店 10:试用 20:正常)
        /// </summary>
        [Description("状态(-10:闭店 10:试用 20:正常)")]
        public int? Status { get; set; }
        /// <summary>
        /// 简介
        /// </summary>
        [Description("简介")]
        public string Describe { get; set; }
        /// <summary>
        /// 联系人
        /// </summary>
        [Description("联系人")]
        public string LinkMan { get; set; }
        /// <summary>
        /// 联系手机
        /// </summary>
        [Description("联系手机")]
        public string Phone { get; set; }
        /// <summary>
        /// 公司名称
        /// </summary>
        [Description("公司名称")]
        public string CompanyName { get; set; }
        /// <summary>
        /// 截止日期
        /// </summary>
        [Description("截止日期")]
        public System.DateTime? DeadLineDate { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        [Browsable(false)]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime? CreateTime { get; set; }
    }
}