//------------------------------------------------------------------------------
// <autogenerated>
//  codeSmith生成代码,别修改.再生成会被覆盖
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

using Qs.Comm.Extensions;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 模块元素表(需要权限控制的按钮)
	/// </summary>
    [Table("ModuleElement")]
    public partial class ModuleElement : StringEntity
    {
        public ModuleElement()
        {
            this.BtnCode = string.Empty;
            this.Name = string.Empty;
            this.Remark = string.Empty;
            this.Sort = 0;
            this.ModuleId = string.Empty;
            this.CreateTime=DateTime.Now;
        }

        /// <summary>
        /// DOM ID
        /// </summary>
        [Description("按钮Code")]
        [Browsable(false)]
        public string BtnCode { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        [Description("名称")]
        public string Name { get; set; }
        
        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        public string Remark { get; set; }
        /// <summary>
        /// 排序字段
        /// </summary>
        [Description("排序字段")]
        public int Sort { get; set; }
        /// <summary>
        /// 功能模块Id
        /// </summary>
        [Description("功能模块Id")]
        [Browsable(false)]
        public string ModuleId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? CreateTime { get; set; }
    }
}