//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using Qs.Repository.Core;

namespace Qs.Repository.Domain
{
    /// <summary>
	/// 角色表
	/// </summary>
      [Table("Role")]
    public partial class Role : StringEntity
    {
        public Role()
        {
          this.Name= string.Empty;
          this.Status= 0;
          this.CreateTime= DateTime.Now;
          this.CreateId= string.Empty;
          this.Type= 0;
        }

        /// <summary>
	    /// 角色名称
	    /// </summary>
         [Description("角色名称")]
        public string Name { get; set; }
        /// <summary>
        /// 类型(10:平台 20:店铺)
        /// </summary>
        [Description("类型(10:平台 20:店铺)")]
        public int Type { get; set; }
        /// <summary>
        /// 当前状态
        /// </summary>
        [Description("状态(-10:停用 10:正常)")]
        public int Status { get; set; }
       
        /// <summary>
	    /// 创建人ID
	    /// </summary>
         [Description("创建人ID")]
        public string CreateId { get; set; }           
        /// <summary>
        /// 店铺Id
        /// </summary>
        [Description("店铺Id")]
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }

    }
}