//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 
	/// </summary>
    public partial class ReqAuCoupon 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int SendType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal MinPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal ReducePrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int ExpireType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? ExpireDay { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime StartTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime EndTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int ApplyRange { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ApplyRangeConfig { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? IsShowHome { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShowImg { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int TotalNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int ReceiveNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Describe { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int LimitQuantity { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int Status { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int Sort { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreId { get; set; }
       
    }
}