//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 特卖会场
	/// </summary>
    public partial class ReqAuSpecialRound 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        
        /// <summary>
        /// 会场名称
        /// </summary>
        public string ExhibitionName { get; set; }
        /// <summary>
        /// 会场列表图片
        /// </summary>
        public string IconImageUrl { get; set; }
        /// <summary>
        /// 会场banner
        /// </summary>
        public string BannerImageUrl { get; set; }
      
    }
}