//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 商品服务承诺
	/// </summary>
    public partial class ReqAuGoodsService 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 服务名称
        /// </summary>
        public string ServiceName { get; set; }
        /// <summary>
        /// 概述
        /// </summary>
        public string Summary { get; set; }
        /// <summary>
        /// 是否默认(10:是 -10:否)
        /// </summary>
        public int? IsDefault { get; set; }
        /// <summary>
        /// 状态 用户端是否展示(10:显示 -10:隐藏)
        /// </summary>
        public string Status { get; set; }
        /// <summary>
        /// 排序(小到大)
        /// </summary>
        public string SortNo { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        public string StoreId { get; set; }
     
    }
}