//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 会员充值订单表
	/// </summary>
    [Table("tb_RechargeOrder")]
    public partial class ReqAuRechargeOrder 
    {

        /// <summary>
        /// 订单Id
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 订单号
        /// </summary>
        public string OrderNo { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        public string UserId { get; set; }
        /// <summary>
        /// 充值方式(10自定义金额 20套餐充值)
        /// </summary>
        public int RechargeType { get; set; }
        /// <summary>
        /// 充值套餐Id
        /// </summary>
        public string PlanId { get; set; }
        /// <summary>
        /// 用户支付金额
        /// </summary>
        public decimal PayPrice { get; set; }
        /// <summary>
        /// 赠送金额
        /// </summary>
        public decimal GiftMoney { get; set; }
        /// <summary>
        /// 实际到账金额
        /// </summary>
        public decimal ActualMoney { get; set; }
        /// <summary>
        /// 支付状态(10待支付 20已支付)
        /// </summary>
        public int PayStatus { get; set; }
        /// <summary>
        /// 付款时间
        /// </summary>
        public System.DateTime PayTime { get; set; }
        /// <summary>
        /// 微信支付交易号
        /// </summary>
        public string TransactionId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public System.DateTime UpdateTime { get; set; }
    }
}