//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 店铺快递
	/// </summary>
    public partial class ReqAuStoreExpress 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 快递公司名
        /// </summary>
        public string ExpressName { get; set; }
        /// <summary>
        /// 快递100Code
        /// </summary>
        public string KuaiDi100Code { get; set; }
        /// <summary>
        /// 快递鸟Code
        /// </summary>
        public string KuaiDiNiaoCode { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int? SortNo { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime? CreateTime { get; set; }
    }
}