//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_Order")]
    public partial class ReqAuOrder 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 订单号
        /// </summary>
        public string OrderNo { get; set; }
        /// <summary>
        /// 订单状态(10:未支付 20:已支付 30:配送中 80:已送达)
        /// </summary>
        public int OrderStatus { get; set; }
        /// <summary>
        /// 商品总金额(不含优惠折扣)
        /// </summary>
        public decimal TotalGoodsPrice { get; set; }
        /// <summary>
        /// 订单金额(含优惠折扣)
        /// </summary>
        public decimal OrderPrice { get; set; }
        /// <summary>
        /// 优惠券ID
        /// </summary>
        public string CouponId { get; set; }
        /// <summary>
        /// 优惠券抵扣金额
        /// </summary>
        public decimal CouponMoney { get; set; }
        /// <summary>
        /// 后台修改的订单金额
        /// </summary>
        public decimal UpdatePrice { get; set; }
        /// <summary>
        /// 实际付款金额(包含运费)
        /// </summary>
        public decimal PayPrice { get; set; }
        /// <summary>
        /// 买家留言
        /// </summary>
        public string BuyerRemark { get; set; }
        /// <summary>
        /// 支付方式(10余额支付 20微信支付 30云闪付)
        /// </summary>
        public int PayType { get; set; }
        /// <summary>
        /// 付款时间
        /// </summary>
        public System.DateTime PayTime { get; set; }
        /// <summary>
        /// 配送方式(10:平台配送 20:自提) 
        /// </summary>
        public int DeliveryType { get; set; }
        /// <summary>
        /// 运费金额
        /// </summary>
        public decimal ExpressPrice { get; set; }
        /// <summary>
        /// 发货时间
        /// </summary>
        public System.DateTime DeliveryTime { get; set; }
        /// <summary>
        /// 赠送的积分数量
        /// </summary>
        public string PointsBonus { get; set; }
        /// <summary>
        /// 支付交易号
        /// </summary>
        public string TransactionId { get; set; }
        /// <summary>
        /// 是否已评价(0否 1是)
        /// </summary>
        public string IsComment { get; set; }
        /// <summary>
        /// 来源客户端 
        /// </summary>
        public string Platform { get; set; }
        /// <summary>
        /// 来源Id(上下级,隔开)
        /// </summary>
        public string SourceUserId { get; set; }
        /// <summary>
        /// 订单来源
        /// </summary>
        public int SourceUser { get; set; }
        /// <summary>
        /// 积分抵扣金额(预留)
        /// </summary>
        public decimal? PointsMoney { get; set; }
        /// <summary>
        /// 积分抵扣数量(预留)
        /// </summary>
        public int? PointsNum { get; set; }
        /// <summary>
        /// 物流公司ID(预留)
        /// </summary>
        public string ExpressId { get; set; }
        /// <summary>
        /// 物流公司(预留)
        /// </summary>
        public string ExpressCompany { get; set; }
        /// <summary>
        /// 物流单号(预留)
        /// </summary>
        public string ExpressNo { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        public string StoreId { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        public string UserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
    }
}