//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 用户优惠券记录表
	/// </summary>
    [Table("tb_UserCoupon")]
    public partial class ReqAuUserCoupon 
    {

        /// <summary>
        /// 主键
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 优惠券Id
        /// </summary>
        public string CouponId { get; set; }
        /// <summary>
        /// 优惠券名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 优惠券类型(10满减券)
        /// </summary>
        public int CouponType { get; set; }
        /// <summary>
        /// 满减券-减免金额
        /// </summary>
        public decimal ReducePrice { get; set; }
        /// <summary>
        /// 最低消费金额
        /// </summary>
        public decimal MinPrice { get; set; }
        /// <summary>
        /// 有效期开始时间
        /// </summary>
        public System.DateTime StartTime { get; set; }
        /// <summary>
        /// 有效期结束时间
        /// </summary>
        public System.DateTime EndTime { get; set; }
        /// <summary>
        /// 适用范围(10全部商品 20指定商品)
        /// </summary>
        public int ApplyRange { get; set; }
        /// <summary>
        /// 适用范围(商品Id,隔开)
        /// </summary>
        public string ApplyRangeConfig { get; set; }
        /// <summary>
        /// 是否过期(-10未过期 10已过期)
        /// </summary>
        public int IsExpire { get; set; }
        /// <summary>
        /// 是否已使用(-10未使用 10已使用)
        /// </summary>
        public int IsUse { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        public string UserId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public System.DateTime UpdateTime { get; set; }
    }
}