//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 
	/// </summary>
    public partial class ReqAuDeliveryRule 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 配送模板ID
        /// </summary>
        public string DeliveryId { get; set; }
        /// <summary>
        /// 可配送区域(城市id集)
        /// </summary>
        public string Region { get; set; }
        /// <summary>
        /// 可配送区域(文字展示)
        /// </summary>
        public string RegionText { get; set; }
        /// <summary>
        /// 首件(个)/首重(Kg)
        /// </summary>
        public decimal First { get; set; }
        /// <summary>
        /// 首个/首重运费(元)
        /// </summary>
        public decimal FirstFee { get; set; }
        /// <summary>
        /// 续件/续重
        /// </summary>
        public decimal Additional { get; set; }
        /// <summary>
        /// 续费(元)
        /// </summary>
        public decimal AdditionalFee { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
    }
}