//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 充值Vip记录
	/// </summary>
    [Table("tb_UserVipLog")]
    public partial class ReqAuUserVipLog 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public string UserId { get; set; }
        /// <summary>
        /// 支付金额
        /// </summary>
        public decimal? PayMoney { get; set; }
        /// <summary>
        /// 开始日期
        /// </summary>
        public System.DateTime? StartDate { get; set; }
        /// <summary>
        /// 结束日期
        /// </summary>
        public System.DateTime? EndDate { get; set; }
        /// <summary>
        /// 支付状态(10待支付 20已支付)
        /// </summary>
        public int PayStatus { get; set; }
        /// <summary>
        /// 付款时间
        /// </summary>
        public System.DateTime PayTime { get; set; }
        /// <summary>
        /// 微信支付交易号
        /// </summary>
        public string TransactionId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
    }
}