//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 商品规格值记录表
	/// </summary>
    [Table("tb_GoodsSpecValue")]
    public partial class ReqAuGoodsSpecValue 
    {

        /// <summary>
        /// 规格值Id
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 规格值
        /// </summary>
        public string SpecValue { get; set; }
        /// <summary>
        /// 规格组Id
        /// </summary>
        public string SpecId { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
    }
}