//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_StorePage")]
    public partial class ReqAuStorePage 
    {
        /// <summary>
        /// Id
        /// </summary>
        public string Id { get; set; }
        public  object Page { get; set; }
        public object Items { get; set; }

        /// <summary>
        /// 页面类型(10首页 20自定义页)
        /// </summary>
        public int? PageType { get; set; }
        /// <summary>
        /// 页面名称
        /// </summary>
        public string PageName { get; set; }
        /// <summary>
        /// 页面数据
        /// </summary>
        public string PageData { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreId { get; set; }
    }

 
}