//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_GoodsSku")]
    public partial class ReqAuGoodsSku 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 商品sku唯一标识 (由规格id组成) 
        /// </summary>
        public string GoodsSkuId { get; set; }
        /// <summary>
        /// 商品Id
        /// </summary>
        public string GoodsId { get; set; }
        /// <summary>
        /// 规格图片Id
        /// </summary>
        public string ImageId { get; set; }
        /// <summary>
        /// Sku编码
        /// </summary>
        public string GoodsSkuNo { get; set; }
        /// <summary>
        /// 商品价格
        /// </summary>
        public decimal GoodsPrice { get; set; }
        /// <summary>
        /// 划线价
        /// </summary>
        public decimal LinePrice { get; set; }
        /// <summary>
        /// 库存数量
        /// </summary>
        public string StockNum { get; set; }
        /// <summary>
        /// 商品重量(Kg)
        /// </summary>
        public decimal GoodsWeight { get; set; }
        /// <summary>
        /// Sku的规格属性(json格式)
        /// </summary>
        public string GoodsProps { get; set; }
        /// <summary>
        /// 规格值ID集(json格式)
        /// </summary>
        public string SpecValueIds { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public System.DateTime UpdateTime { get; set; }
    }
}