//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 用户积分变动明细
	/// </summary>
    public partial class ReqAuUserPointsLog 
    {

        /// <summary>
        /// 主键Id
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 用户Id
        /// </summary>
        public string UserId { get; set; }
        /// <summary>
        /// 订单ID(可选)
        /// </summary>
        public string OrderId { get; set; }
        /// <summary>
        /// 余额变动场景(10:用户充值 11:管理员充值 20:用户消费 21:管理员扣减 31:管理员设置余额 40:订单退款)
        /// </summary>
        public int Scene { get; set; }
        /// <summary>
        /// 变动积分
        /// </summary>
        public decimal Points { get; set; }
        /// <summary>
        /// 操作后积分
        /// </summary>
        public decimal? BalancePoints { get; set; }
        /// <summary>
        /// 描述/说明
        /// </summary>
        public string Describe { get; set; }
        /// <summary>
        /// 管理员备注
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 店铺Id
        /// </summary>
        public string StoreId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
    }
}