//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Comm;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
    /// 用户收货地址表
    /// </summary>
    public partial class ReqAuUserAddressSetDefault
    {
        /// <summary>
        /// 主键Id
        /// </summary>
        public string Id { get; set; }


        public void Check()
        {

            xValidation.CheckStrNull(new List<ValueTip>()
            {
                new ValueTip(Id, "Id"),
            });
        }



    }
}