//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Comm;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
    /// 用户收货地址表
    /// </summary>
    [Table("tb_UserAddress")]
    public partial class ReqAddOrUpdateNormal
    {

        /// <summary>
        /// 主键Id
        /// </summary>
        public string Id { get; set; }
        
        /// <summary>
        /// 收货人姓名
        /// </summary>
        public string LinkMan { get; set; }
        /// <summary>
        /// 联系电话
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 省市区地址
        /// </summary>
        public string StrProvince { get; set; }
        /// <summary>
        /// 详细地址
        /// </summary>
        public string Detail { get; set; }

        /// <summary>
        /// 是否默认
        /// </summary>
        public bool IsDefault { get; set; }

        /// <summary>
        ///经度
        /// </summary>
        public decimal? Longitude { get; set; }
        /// <summary>
        ///纬度
        /// </summary>
        public decimal? Latitude { get; set; }

        public void Check()
        {

            xValidation.CheckStrNull(new List<ValueTip>()
            {
                
                new ValueTip(LinkMan,"联系人"),
                new ValueTip(Phone,"手机号"),
                new ValueTip(StrProvince,"省市区"),
                new ValueTip(Detail,"详细地址"),

            });
            xValidation.CheckPhone(Phone);
        }

    }
}