//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Comm;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 
	/// </summary>
    public partial class ReqAuChangeCateStatus
    {

        /// <summary>
        ///  ID
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 是否首页展示
        /// </summary>
        public int Status { get; set; }

        public void Check()
        {
            xValidation.CheckStrNull(new List<ValueTip>()
            {
                new ValueTip(Id,"Id")
            });
            xValidation.CheckIntNull(Status, "是否首页展示");
        }
    }
}