//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_InviteLinkRecord")]
    public partial class ReqAuInviteLinkRecord 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LinkId { get; set; }
        /// <summary>
        /// 邀请人Id
        /// </summary>
        public string InviterId { get; set; }
        /// <summary>
        /// 邀请人名称
        /// </summary>
        public string InviterName { get; set; }
        /// <summary>
        /// 邀请人手机号
        /// </summary>
        public string InviterPhone { get; set; }
        /// <summary>
        /// 被邀请人Uid
        /// </summary>
        public string InviteeUid { get; set; }
        /// <summary>
        /// 被邀请人名称
        /// </summary>
        public string InviteeName { get; set; }
        /// <summary>
        /// 被邀请人手机号码
        /// </summary>
        public string InviteePhone { get; set; }
        /// <summary>
        /// 被邀请人代金券金额(预留)
        /// </summary>
        public decimal InviteeCouponAmout { get; set; }
        /// <summary>
        /// 优惠券数量
        /// </summary>
        public int InviteeCouponQuantity { get; set; }
        /// <summary>
        /// 是否已发送邀请人代金券
        /// </summary>
        public int IsSendInviterCoupon { get; set; }
        /// <summary>
        /// 是否已发送被邀请人代金券
        /// </summary>
        public int IsSendInviteeCoupon { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
    }
}