//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.App.Request
{
    /// <summary>
	/// 粉丝关注
	/// </summary>
    public partial class ReqAuFocus
    {
          /// <summary>
          /// 直播间Id
          /// </summary>
       public string RoomId { get; set; }
        
         
    }
}