//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Comm;
using Qs.Repository.Core;

namespace Qs.App.Request
{
    /// <summary>
	/// 系统日志
	/// </summary>
    [Table("SysLog")]
    public partial class ReqAuSysLog 
    {      
        /// <summary>
        /// Id
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 日志内容
        /// </summary>
        public string Content { get; set; }
        /// <summary>
        /// 类型(10:操作日志 20:接口日志 30:错误日志)
        /// </summary>
        public int? Type { get; set; }
        /// <summary>
        /// 日志等级(50:严重错误 40:错误 30:警告 20:消息)
        /// </summary>
        public xEnum.LogLevel LogLevel { get; set; }
        /// <summary>
        /// 操作所属模块地址
        /// </summary>
        public string Href { get; set; }
        /// <summary>
        /// 操作的结果：0：成功；1：失败；
        /// </summary>
        public int Result { get; set; }
        /// <summary>
        /// 输入
        /// </summary>
        public string ApiInContent { get; set; }
        /// <summary>
        /// 输出
        /// </summary>
        public string ApiOutContent { get; set; }
        /// <summary>
        /// 操作机器的IP地址
        /// </summary>
        public string Ip { get; set; }
        /// <summary>
        /// 所属应用
        /// </summary>
        public string Application { get; set; }
        /// <summary>
        /// 记录时间
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 操作人ID
        /// </summary>
        public string CreateId { get; set; }
        /// <summary>
        /// 操作人
        /// </summary>
        public string CreateName { get; set; }
        
         
    }
}