//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_InvitePoster")]
    public partial class ReqAuInvitePoster 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PosterName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ImageId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? CountRegUser { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public string UserId { get; set; }
       
    }
}