//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 购物车
	/// </summary>
    [Table("tb_Cart")]
    public partial class ReqAuCart 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GoodsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GoodsSkuId { get; set; }
        
        /// <summary>
        /// 商品数量
        /// </summary>
        public int GoodsNum { get; set; }
    }
}