//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
    /// 商品评价
    /// </summary>
    public partial class ReqAuGoodsComment
    {  
        /// <summary>
        /// 订单ID
        /// </summary>
         public string OrderId { get; set; }

         /// <summary>
         /// 商品评价
         /// </summary>
         public List<GoodsComment> ListComment { get; set; }
    }

    /// <summary>
    /// 商品评价
    /// </summary>
    public class GoodsComment
    {
        /// <summary>
        /// 商品Id
        /// </summary>
        public string GoodsId { get; set; }
        /// <summary>
        /// SkuId
        /// </summary>
        public string SkuId { get; set; }

        /// <summary>
        /// 评价分数
        /// </summary>
        public int RateValue { get; set; }

        /// <summary>
        /// 评价内容
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 图片Id
        /// </summary>
        public List<string> Uploaded { get; set; }
    }
}