//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Comm;
using Qs.Repository.Base;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
    /// 创建订单
    /// </summary>
    [Table("tb_Order")]
    public partial class ReqConfirmOrder : BaseReqAu
    {
        /// <summary>
        /// AppUser:用户端 AppBusiness:业务员 AppDriver:司机 AppDispatch:调度
        /// </summary>
        public string AppKey { get; set; }

        /// <summary>
        /// 订单Id
        /// </summary>
        public string OrderId { get; set; }

        /// <summary>
        /// 地址Id
        /// </summary>
        public string AddressId { get; set; }

        /// <summary>
        /// 买家留言(备注)
        /// </summary>
        public string BuyerRemark { get; set; }

        /// <summary>
        /// 用户优惠券ID
        /// </summary>
        public string UserCouponId { get; set; }

        /// <summary>
        /// 支付方式(10余额支付 20微信支付 30云闪付 50:找人代付)
        /// </summary>
        public int PayType { get; set; }

        // /// <summary>
        // /// 余额支付密码
        // /// </summary>
        // public string BalancePwd { get; set; }

        /// <summary>
        /// 参数验证
        /// </summary>
        public void Check()
        {
            xValidation.CheckStrNull(new List<ValueTip>()
            {
                new ValueTip(AddressId, "配送地址不能为空")
            });
            xValidation.CheckStrNull(new List<ValueTip>()
            {
                new ValueTip(OrderId, "订单Id"),
            });
            xValidation.CheckIntNull(PayType, "支付类型");
            // if (PayType == (int) xEnum.PayType.Balance && string.IsNullOrEmpty(BalancePwd))
            // {
            //     throw new Exception("余额支付密码不能为空");
            // }
        }
    }
}