//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 
	/// </summary>
    [Table("tb_GoodsSku")]
    public partial class ReqListChangeSkuPrice
    {

         public List<ReqChangeSkuPrice> List { get; set; }
    }


    public class ReqChangeSkuPrice
    {
        /// <summary>
        /// GoodsSkuId
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 商品ID
        /// </summary>
        public string GoodsId { get; set; }
        /// <summary>
        /// 商品价格
        /// </summary>
        public decimal SalePrice { get; set; }
    }
}