//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Comm;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
    /// 获取支付参数
    /// </summary>
    public partial class ReqGetPayParam
    {
        /// <summary>
        /// AppUser:用户端 AppBusiness:业务员 AppDriver:司机 AppDispatch:调度
        /// </summary>
        public string AppKey { get; set; }
        /// <summary>
        /// 订单Id
        /// </summary>
        public string OrderId { get; set; }
                                             
        /// <summary>
        /// 支付方式(10余额支付 20微信支付 30云闪付 50:找人代付)
        /// </summary>
        public int PayType { get; set; }
        /// <summary>
        /// 余额支付密码
        /// </summary>
        public string BalancePwd { get; set; }

        /// <summary>
        /// 参数验证
        /// </summary>
        public void Check()
        {
            xValidation.CheckStrNull(new List<ValueTip>()
            {
                new ValueTip(OrderId,"订单Id")  ,
            });
            if (PayType == (int) xEnum.PayType.Balance && string.IsNullOrEmpty(BalancePwd))
            {
                throw new Exception("余额支付密码不能为空");
            }
        }
    }
}