//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

using Qs.Comm;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	///  退货 发货
	/// </summary>
    public partial class ReqRefundDelivery
    {

        /// <summary>
        /// OrderRefundSkuId
        /// </summary>
        public string OrderRefundSkuId { get; set; }
        /// <summary>
        /// 快递公司
        /// </summary>
        public string ExpressId { get; set; }
        /// <summary>
        /// 快递单号
        /// </summary>
        public string ExpressNo { get; set; }

        public void Check()
        {
            xValidation.CheckStrNull(OrderRefundSkuId, "Id");
            xValidation.CheckStrNull(ExpressId, "快递公司");
            xValidation.CheckStrNull(ExpressNo, "快递单号");
        }
    }
}