//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Qs.Repository.Core;

namespace Qs.Repository.Request
{
    /// <summary>
	/// 店铺表
	/// </summary>
    public partial class ReqUpdateStore
    {
        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 商城名称
        /// </summary>
        public string StoreName { get; set; }
        /// <summary>
        /// 简介
        /// </summary>
        public string Describe { get; set; }
        /// <summary>
        /// Logo
        /// </summary>
        public string LogoImageId { get; set; }
    }
}